apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-config
spec:
  template:
    metadata:
      labels:
        app: batch-pod
    spec:
      restartPolicy: OnFailure
      containers:
      - name: batch-container
        image: ardconsulting/test:jobenv
        envFrom:
        - configMapRef: 
            name: my-config2