apiVersion: v1
kind: PersistentVolume
metadata: 
  name: local-volume
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath: 
    path: "/tmp/mongodata"
  