apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-env
spec:
  template:
    metadata:
      labels:
        app: batch-pod
    spec:
      restartPolicy: OnFailure
      containers:
      - name: batch-container
        image: ardconsulting/test:jobenv
        env:
        - name: EXAMPLEVAR
          value: "30"