apiVersion: v1
kind: ReplicationController
metadata: 
  name: nodeapp-rc
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: ardconsulting/test:nodeapp
        name: nodeapp-container
        ports:
        - containerPort: 8091
          protocol: TCP