apiVersion: v1
kind: Pod
metadata: 
    name: nodeapp-pod
    namespace: custom-namespace
spec:
    containers:
    - image: ardconsulting/test:nodeapp
      name: nodeapp-container
      ports:
      - containerPort: 8091
        protocol: TCP